import { NextResponse } from "next/server";
import { auth } from "~/server/auth";

// 1:1 copy of /backend/src/caption_templates.py — CAPTION_TEMPLATES dict
// NOTE: font_size values are ASS pt units at PlayResY:1920, NOT CSS pixels.
// A value of 75 renders ~75px tall on a 1920px-high video frame.
const CAPTION_TEMPLATES = [
  {
    id: "default",
    name: "Default",
    description: "Clean white text with black outline",
    animation: "none",
    font_family: "THEBOLDFONT",
    font_size: 70,
    font_color: "#FFFFFF",
    highlight_color: "#FFD700",
    stroke_color: "#000000",
    stroke_width: 2,
    background: false,
    background_color: null,
    shadow: false,
    position_y: 0.75,
  },
  {
    id: "hormozi",
    name: "Hormozi",
    description: "Bold green highlights like Alex Hormozi's videos",
    animation: "karaoke",
    font_family: "THEBOLDFONT",
    font_size: 75,
    font_color: "#FFFFFF",
    highlight_color: "#00FF00",
    stroke_color: "#000000",
    stroke_width: 3,
    background: true,
    background_color: "#000000AA",
    shadow: true,
    position_y: 0.75,
  },
  {
    id: "mrbeast",
    name: "MrBeast",
    description: "Large yellow text with red highlights",
    animation: "pop",
    font_family: "THEBOLDFONT",
    font_size: 88,
    font_color: "#FFFF00",
    highlight_color: "#FF0000",
    stroke_color: "#000000",
    stroke_width: 4,
    background: false,
    background_color: null,
    shadow: true,
    position_y: 0.7,
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Clean, subtle captions with transparent background",
    animation: "fade",
    font_family: "TikTokSans-Regular",
    font_size: 58,
    font_color: "#FFFFFF",
    highlight_color: "#CCCCCC",
    stroke_color: null,
    stroke_width: 0,
    background: true,
    background_color: "#00000080",
    shadow: false,
    position_y: 0.8,
  },
  {
    id: "tiktok",
    name: "TikTok",
    description: "TikTok-style with pink highlights",
    animation: "karaoke",
    font_family: "TikTokSans-Regular",
    font_size: 70,
    font_color: "#FFFFFF",
    highlight_color: "#FE2C55",
    stroke_color: "#000000",
    stroke_width: 2,
    background: false,
    background_color: null,
    shadow: true,
    position_y: 0.75,
  },
  {
    id: "neon",
    name: "Neon",
    description: "Glowing neon effect with cyan highlights",
    animation: "karaoke",
    font_family: "THEBOLDFONT",
    font_size: 72,
    font_color: "#00FFFF",
    highlight_color: "#FF00FF",
    stroke_color: "#000066",
    stroke_width: 2,
    background: false,
    background_color: null,
    shadow: true,
    position_y: 0.75,
  },
  {
    id: "podcast",
    name: "Podcast",
    description: "Professional podcast-style captions",
    animation: "fade",
    font_family: "TikTokSans-Regular",
    font_size: 62,
    font_color: "#FFFFFF",
    highlight_color: "#FFB800",
    stroke_color: "#333333",
    stroke_width: 1,
    background: true,
    background_color: "#1A1A1ACC",
    shadow: false,
    position_y: 0.78,
  },
];

export async function GET() {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  return NextResponse.json({ templates: CAPTION_TEMPLATES });
}
